In [1]:
import tensorflow as tf


## creating a constant tensor

In [2]:
# creating a constant tensor
con = tf.constant([[1,2,3,4,5,6]], shape = [3,2], dtype = tf.float32)
con


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>

In [3]:
zer =tf.zeros(shape = [3,4], dtype = tf.float32)
zer

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [4]:
zeros_like_zer = tf.zeros_like(zer)
zeros_like_zer.numpy()

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [5]:
zerr = tf.zeros_like(5)
zerr

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [6]:
# tensor to fill with specific value
tf_f = tf.fill([2,3], 77)
tf_f.numpy()

array([[77, 77, 77],
       [77, 77, 77]], dtype=int32)

In [7]:
# to create a tensor with specific distribution
tf_normal = tf.random.normal([4,4], mean= 0.0, stddev = 0.1, seed = 2)
tf_normal.numpy()

array([[-0.08581109, -0.0196623 ,  0.01389505, -0.12212767],
       [-0.04034128, -0.11454041,  0.0639824 , -0.15766118],
       [-0.10260107,  0.06285083, -0.08282237,  0.03466772],
       [ 0.13986593,  0.10717978,  0.12229327, -0.00728902]],
      dtype=float32)

In [8]:
tf_uniform = tf.random.uniform([4,4], minval = 3, maxval =9)
tf_uniform.numpy()

array([[3.6492054, 6.266268 , 4.1278453, 3.8220477],
       [3.3197129, 7.733303 , 8.173481 , 8.729217 ],
       [5.671587 , 8.835883 , 7.62893  , 3.6541793],
       [6.4062243, 6.9006987, 8.360431 , 5.1722775]], dtype=float32)

In [9]:
# converting list into tensor

list_f  = [2,3,5,7,21,34,98]
type(list_f)
tf_list = tf.convert_to_tensor(list_f, dtype = tf.float32)
tf_list.numpy()

array([ 2.,  3.,  5.,  7., 21., 34., 98.], dtype=float32)

## creating a variable tensor

In [10]:
var_1  = tf.Variable(tf.ones([2,3]))
var_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

## tensor slicing and indexing

In [11]:
# slicing
# 4 dimension

tf_h = tf.random.normal([4,100,100,3])
tf_h

<tf.Tensor: shape=(4, 100, 100, 3), dtype=float32, numpy=
array([[[[ 1.07650709e+00, -1.72730848e-01, -5.21686971e-01],
         [ 3.84941041e-01, -2.72450238e-01,  1.04472828e+00],
         [ 1.38815731e-01,  7.07204163e-01,  6.70788467e-01],
         ...,
         [ 4.49149102e-01, -1.22007287e+00,  7.64108956e-01],
         [-1.23683929e+00,  3.38297099e-01, -1.17301536e+00],
         [-7.59532452e-01, -9.22050849e-02, -2.41515231e+00]],

        [[-2.32188851e-01, -2.24540174e-01,  2.71750391e-01],
         [-3.55955720e-01,  1.37921929e-01, -1.83559263e+00],
         [ 4.37345386e-01,  1.12312210e+00,  9.30488408e-02],
         ...,
         [-8.28335062e-02,  1.63837850e-01, -3.22711110e-01],
         [-1.26928198e+00, -1.14864671e+00, -9.87197936e-01],
         [-5.10334551e-01, -1.20736289e+00,  8.97690177e-01]],

        [[-5.27785681e-02, -1.84772030e-01, -5.50617158e-01],
         [-1.75783134e+00,  5.55702448e-01,  2.91485518e-01],
         [ 1.20704724e-02, -1.94878191e-01

In [12]:
# extracting first element
tf_h[0,:,:,:]

<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
array([[[ 1.0765071 , -0.17273085, -0.521687  ],
        [ 0.38494104, -0.27245024,  1.0447283 ],
        [ 0.13881573,  0.70720416,  0.67078847],
        ...,
        [ 0.4491491 , -1.2200729 ,  0.76410896],
        [-1.2368393 ,  0.3382971 , -1.1730154 ],
        [-0.75953245, -0.09220508, -2.4151523 ]],

       [[-0.23218885, -0.22454017,  0.2717504 ],
        [-0.35595572,  0.13792193, -1.8355926 ],
        [ 0.4373454 ,  1.1231221 ,  0.09304884],
        ...,
        [-0.08283351,  0.16383785, -0.3227111 ],
        [-1.269282  , -1.1486467 , -0.98719794],
        [-0.51033455, -1.2073629 ,  0.8976902 ]],

       [[-0.05277857, -0.18477203, -0.55061716],
        [-1.7578313 ,  0.55570245,  0.29148552],
        [ 0.01207047, -0.19487819, -0.48408234],
        ...,
        [ 0.05786728,  0.44004086, -1.9789615 ],
        [-0.52572596, -0.45688272,  0.14927931],
        [ 0.6029995 ,  0.06406065, -0.42193213]],

       ...,

     

In [13]:
tf_h[::2,...]

<tf.Tensor: shape=(2, 100, 100, 3), dtype=float32, numpy=
array([[[[ 1.0765071 , -0.17273085, -0.521687  ],
         [ 0.38494104, -0.27245024,  1.0447283 ],
         [ 0.13881573,  0.70720416,  0.67078847],
         ...,
         [ 0.4491491 , -1.2200729 ,  0.76410896],
         [-1.2368393 ,  0.3382971 , -1.1730154 ],
         [-0.75953245, -0.09220508, -2.4151523 ]],

        [[-0.23218885, -0.22454017,  0.2717504 ],
         [-0.35595572,  0.13792193, -1.8355926 ],
         [ 0.4373454 ,  1.1231221 ,  0.09304884],
         ...,
         [-0.08283351,  0.16383785, -0.3227111 ],
         [-1.269282  , -1.1486467 , -0.98719794],
         [-0.51033455, -1.2073629 ,  0.8976902 ]],

        [[-0.05277857, -0.18477203, -0.55061716],
         [-1.7578313 ,  0.55570245,  0.29148552],
         [ 0.01207047, -0.19487819, -0.48408234],
         ...,
         [ 0.05786728,  0.44004086, -1.9789615 ],
         [-0.52572596, -0.45688272,  0.14927931],
         [ 0.6029995 ,  0.06406065, -0.4219321

In [14]:
# indexing
#Obtain the pixel in the position [20,40] in the second channel of the first image.
tf_h[0][19][39][1]

<tf.Tensor: shape=(), dtype=float32, numpy=-2.197584>

In [15]:
# extract pixel of first ,second and fouth image  tf_h
indices = [0,1,3]
tf.gather(tf_h, indices = indices,batch_dims = 1 , axis =0)

<tf.Tensor: shape=(3, 100, 100, 3), dtype=float32, numpy=
array([[[[ 1.07650709e+00, -1.72730848e-01, -5.21686971e-01],
         [ 3.84941041e-01, -2.72450238e-01,  1.04472828e+00],
         [ 1.38815731e-01,  7.07204163e-01,  6.70788467e-01],
         ...,
         [ 4.49149102e-01, -1.22007287e+00,  7.64108956e-01],
         [-1.23683929e+00,  3.38297099e-01, -1.17301536e+00],
         [-7.59532452e-01, -9.22050849e-02, -2.41515231e+00]],

        [[-2.32188851e-01, -2.24540174e-01,  2.71750391e-01],
         [-3.55955720e-01,  1.37921929e-01, -1.83559263e+00],
         [ 4.37345386e-01,  1.12312210e+00,  9.30488408e-02],
         ...,
         [-8.28335062e-02,  1.63837850e-01, -3.22711110e-01],
         [-1.26928198e+00, -1.14864671e+00, -9.87197936e-01],
         [-5.10334551e-01, -1.20736289e+00,  8.97690177e-01]],

        [[-5.27785681e-02, -1.84772030e-01, -5.50617158e-01],
         [-1.75783134e+00,  5.55702448e-01,  2.91485518e-01],
         [ 1.20704724e-02, -1.94878191e-01

## Tensor Dimension Reduction

In [17]:
# Tensor display
const_d = tf.constant([[1,2,3,4]], shape =[2,2], dtype = tf.float32)
print(const_d.shape)


(2, 2)
(2, 2)


In [18]:
print(const_d.get_shape())

(2, 2)


In [19]:
print(tf.shape(const_d))

tf.Tensor([2 2], shape=(2,), dtype=int32)


In [20]:
# Dimension Reshaping
reshape_1 = tf.constant([[1,2,3],[4,5,6]])
print(reshape_1)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [21]:
print(tf.reshape(reshape_1, (3,2)))

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [22]:
# Dimension Expansion

expansion_sample_1 = tf.random.normal([100,100,3], seed = 1)

In [24]:
print("The size of original of original data :" ,expansion_sample_1.shape)

The size of original of original data : (100, 100, 3)


In [25]:
print("add a dimension before the first dimension (axis = 0):",tf.expand_dims(expansion_sample_1, axis=0).shape)

add a dimension before the first dimension (axis = 0): (1, 100, 100, 3)


In [27]:
print("add a dimension before the second dimension (axis =1):", tf.expand_dims(expansion_sample_1, axis=1).shape)

add a dimension before the second dimension (axis =1): (100, 1, 100, 3)


In [28]:
print("add a dimension after the last dimension (axis = -1):",tf.expand_dims(expansion_sample_1,axis=-1).shape)

add a dimension after the last dimension (axis = -1): (100, 100, 3, 1)


In [31]:
#Transpose
transpose_1 = tf.constant([[1,2,3,4,5,6]], shape = (2,3))
print("The size of the original data",transpose_1.shape)

The size of the original data (2, 3)


In [32]:
transpose_sample = tf.transpose(transpose_1)
print("the size of transposed data:",transpose_sample)

the size of transposed data: tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


## Arithmetic Operations on Tensors

In [34]:
a = tf.constant([[3, 5], [4, 8]])
b = tf.constant([[1, 6], [2, 9]])
print(tf.add(a, b))

tf.Tensor(
[[ 4 11]
 [ 6 17]], shape=(2, 2), dtype=int32)


In [35]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 63],
       [20, 96]], dtype=int32)>

## Dimension-based Arithmetic Operations

In [36]:
reduce_sample_1 = tf.constant([1,2,3,4,5,6],shape=[2,3])
print("original data",reduce_sample_1.numpy())

original data [[1 2 3]
 [4 5 6]]


In [37]:
print("calculate the sum of all elements in the tensor (axis = None):",tf.reduce_sum(reduce_sample_1,axis=None).numpy())

calculate the sum of all elements in the tensor (axis = None): 21


In [38]:
print("calculate the sum of elements in each column by column (axis = 0):",tf.reduce_sum(reduce_sample_1,axis=0).numpy())

calculate the sum of elements in each column by column (axis = 0): [5 7 9]


In [39]:
print("calculate the sum of elements in each column by row (axis = 1):",tf.reduce_sum(reduce_sample_1,axis=1).numpy())

calculate the sum of elements in each column by row (axis = 1): [ 6 15]


## Tensor Concatenation and Splitting

In [41]:
# Tensor Concatenation
concat_sample_1 = tf.random.normal([4,100,100,3])
concat_sample_2 = tf.random.normal([40,100,100,3])
print("the size of concatnated data:", tf.concat([concat_sample_1, concat_sample_2],axis =0).shape)

the size of concatnated data: (44, 100, 100, 3)


In [45]:
stack_sample_1 = tf.random.normal([100,100,3])
stack_sample_2 = tf.random.normal([100,100,3])
print("sizes of the original data: ",stack_sample_1.shape, stack_sample_2.shape)

sizes of the original data:  (100, 100, 3) (100, 100, 3)


In [46]:
#Dimensions increase after the concatenation. If axis is set to 0, a dimension is added before the first dimension.
stacked_sample_1 = tf.stack([stack_sample_1, stack_sample_2],axis=0)
print("size of the concatenated data:",stacked_sample_1.shape)

size of the concatenated data: (2, 100, 100, 3)


In [ ]:
# Tensor Splitting
# tf.unstack(): splits a tensor by a specific dimension

# tf.split(): splits a tensor into a specified number of sub tensors based on a specific dimension.
# tf.split() is more flexible than tf.unstack().

In [47]:
#Split data based on the first dimension and output the split data in a list.
tf.unstack(stacked_sample_1,axis=0)

[<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
 array([[[-1.0931232 , -0.17761314,  1.8224361 ],
         [-0.0702137 , -0.13156016,  0.34018326],
         [ 2.2298634 , -0.30032945, -0.67547596],
         ...,
         [-0.9613664 , -0.37185803,  1.3116527 ],
         [ 0.9526879 , -0.53846157, -0.00560764],
         [-0.01393238, -0.21990484, -0.33502802]],
 
        [[ 0.87278455,  1.8807921 ,  0.6421337 ],
         [ 1.4684571 ,  1.633634  ,  0.6963396 ],
         [ 0.7193649 ,  0.7641671 , -0.86697257],
         ...,
         [ 0.32449278, -0.74273056,  0.10595667],
         [ 0.22060089, -0.05237322, -0.44181094],
         [ 0.69634694, -0.07323229,  0.8010344 ]],
 
        [[ 2.6197054 ,  1.5575117 , -0.3963312 ],
         [ 0.3903374 ,  0.00567671, -1.2535615 ],
         [-0.17707177,  0.8120808 , -1.244008  ],
         ...,
         [-2.3860617 , -1.6669099 ,  0.40648338],
         [-0.69309515,  1.922485  , -1.184694  ],
         [ 0.5756418 ,  0.28732872,  0.2679079

In [48]:
import numpy as np
split_sample_1 = tf.random.normal([10,100,100,3])
print("size of the original data:",split_sample_1.shape)
splited_sample_1 = tf.split(split_sample_1, num_or_size_splits=5,axis=0)
print("size of the split data when m_or_size_splits is set to 10: ",np.shape(splited_sample_1))
splited_sample_2 = tf.split(split_sample_1, num_or_size_splits=[3,5,2],axis=0)
print("sizes of the split data when num_or_size_splits is set to [3,5,2]:",
np.shape(splited_sample_2[0]),
np.shape(splited_sample_2[1]),
np.shape(splited_sample_2[2]))

size of the original data: (10, 100, 100, 3)
size of the split data when m_or_size_splits is set to 10:  (5, 2, 100, 100, 3)
sizes of the split data when num_or_size_splits is set to [3,5,2]: (3, 100, 100, 3) (5, 100, 100, 3) (2, 100, 100, 3)


## Tensor Sorting

In [ ]:
#tf.sort(): sorts tensors in ascending or descending order and returns the sorted tensors.
# tf.argsort(): sorts tensors in ascending or descending order, and returns tensor indexes.
# tf.nn.top_k(): returns the first k maximum values.tf.sort/argsort(input, direction, axis):
# input: input tensor direction: sorting order, which can be set to DESCENDING (descending order) or ASCENDING (ascending order). The default value is ASCENDING.


In [52]:
sort_sample_1 = tf.random.shuffle(tf.range(10))
print('input sample:', sort_sample_1.numpy())

input sample: [6 2 7 0 3 1 4 9 8 5]


In [53]:
sorted_sample_1 = tf.sort(sort_sample_1, direction="ASCENDING")
print("tensor sorted in ascending order:",sorted_sample_1.numpy())

tensor sorted in ascending order: [0 1 2 3 4 5 6 7 8 9]


In [54]:
sorted_sample_2 = tf.argsort(sort_sample_1,direction="ASCENDING")
print("indexes of elements in ascending order:",sorted_sample_2.numpy())

indexes of elements in ascending order: [3 5 1 4 6 9 0 2 8 7]


In [56]:
values, index = tf.nn.top_k(sort_sample_1,5)
print("input tensor:",sort_sample_1.numpy())

input tensor: [6 2 7 0 3 1 4 9 8 5]


In [57]:
print("first five values in ascending order:", values.numpy())

first five values in ascending order: [9 8 7 6 5]


In [58]:
print("indexes of the first five values in ascending order:", index.numpy())

indexes of the first five values in ascending order: [7 8 2 0 9]


In [ ]:
## AutoGraph of TensorFlow 2.x