In [1]:
import tensorflow as tf


## creating a constant tensor

In [2]:
# creating a constant tensor
con = tf.constant([[1,2,3,4,5,6]], shape = [3,2], dtype = tf.float32)
con


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>

In [3]:
zer =tf.zeros(shape = [3,4], dtype = tf.float32)
zer

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [4]:
zeros_like_zer = tf.zeros_like(zer)
zeros_like_zer.numpy()

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [5]:
zerr = tf.zeros_like(5)
zerr

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [6]:
# tensor to fill with specific value
tf_f = tf.fill([2,3], 77)
tf_f.numpy()

array([[77, 77, 77],
       [77, 77, 77]], dtype=int32)

In [7]:
# to create a tensor with specific distribution
tf_normal = tf.random.normal([4,4], mean= 0.0, stddev = 0.1, seed = 2)
tf_normal.numpy()

array([[-0.08581109, -0.0196623 ,  0.01389505, -0.12212767],
       [-0.04034128, -0.11454041,  0.0639824 , -0.15766118],
       [-0.10260107,  0.06285083, -0.08282237,  0.03466772],
       [ 0.13986593,  0.10717978,  0.12229327, -0.00728902]],
      dtype=float32)

In [8]:
tf_uniform = tf.random.uniform([4,4], minval = 3, maxval =9)
tf_uniform.numpy()

array([[8.034698 , 4.7970486, 5.9789267, 7.481987 ],
       [6.603447 , 3.5696769, 3.6318333, 4.034877 ],
       [8.094272 , 7.991847 , 4.1275387, 7.2014623],
       [3.7006588, 3.7608283, 4.0240183, 7.6883335]], dtype=float32)

In [9]:
# converting list into tensor

list_f  = [2,3,5,7,21,34,98]
type(list_f)
tf_list = tf.convert_to_tensor(list_f, dtype = tf.float32)
tf_list.numpy()

array([ 2.,  3.,  5.,  7., 21., 34., 98.], dtype=float32)

## creating a variable tensor

In [10]:
var_1  = tf.Variable(tf.ones([2,3]))
var_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

## tensor slicing and indexing

In [11]:
# slicing
# 4 dimension

tf_h = tf.random.normal([4,100,100,3])
tf_h

<tf.Tensor: shape=(4, 100, 100, 3), dtype=float32, numpy=
array([[[[-9.35104370e-01,  9.06013727e-01, -1.41246632e-01],
         [-4.87768531e-01, -1.75401282e+00, -5.94542205e-01],
         [ 1.45432043e+00, -7.86842406e-02,  8.64428937e-01],
         ...,
         [-7.24449232e-02, -1.14354110e+00, -1.66517571e-01],
         [ 1.07311934e-01, -1.43393064e+00,  1.27602649e+00],
         [-2.57957280e-01, -1.21327472e+00,  5.22767365e-01]],

        [[-1.02068134e-01,  1.20898390e+00,  2.86469877e-01],
         [-2.25056097e-01,  1.14680910e+00, -9.38794076e-01],
         [-2.71305352e-01,  4.42429781e-01,  5.90945125e-01],
         ...,
         [ 4.86484051e-01,  5.65834403e-01, -1.33230790e-01],
         [-7.41499901e-01,  3.27525198e-01,  9.48064029e-01],
         [-9.35869038e-01, -1.94533989e-01, -4.77605283e-01]],

        [[ 2.32106194e-01,  5.77678621e-01,  3.80625837e-02],
         [ 1.10020924e+00,  3.64400446e-01,  2.60015756e-01],
         [ 8.34384441e-01, -1.44485846e-01

In [12]:
# extracting first element
tf_h[0,:,:,:]

<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
array([[[-0.93510437,  0.9060137 , -0.14124663],
        [-0.48776853, -1.7540128 , -0.5945422 ],
        [ 1.4543204 , -0.07868424,  0.86442894],
        ...,
        [-0.07244492, -1.1435411 , -0.16651757],
        [ 0.10731193, -1.4339306 ,  1.2760265 ],
        [-0.25795728, -1.2132747 ,  0.52276736]],

       [[-0.10206813,  1.2089839 ,  0.28646988],
        [-0.2250561 ,  1.1468091 , -0.9387941 ],
        [-0.27130535,  0.44242978,  0.5909451 ],
        ...,
        [ 0.48648405,  0.5658344 , -0.13323079],
        [-0.7414999 ,  0.3275252 ,  0.948064  ],
        [-0.93586904, -0.19453399, -0.47760528]],

       [[ 0.2321062 ,  0.5776786 ,  0.03806258],
        [ 1.1002092 ,  0.36440045,  0.26001576],
        [ 0.83438444, -0.14448585,  1.4778316 ],
        ...,
        [-0.82248026, -1.2253575 ,  1.4254991 ],
        [-0.85262907,  0.41728052,  0.40076151],
        [-0.12650366, -0.3388245 , -1.1100459 ]],

       ...,

     

In [13]:
tf_h[::2,...]

<tf.Tensor: shape=(2, 100, 100, 3), dtype=float32, numpy=
array([[[[-0.93510437,  0.9060137 , -0.14124663],
         [-0.48776853, -1.7540128 , -0.5945422 ],
         [ 1.4543204 , -0.07868424,  0.86442894],
         ...,
         [-0.07244492, -1.1435411 , -0.16651757],
         [ 0.10731193, -1.4339306 ,  1.2760265 ],
         [-0.25795728, -1.2132747 ,  0.52276736]],

        [[-0.10206813,  1.2089839 ,  0.28646988],
         [-0.2250561 ,  1.1468091 , -0.9387941 ],
         [-0.27130535,  0.44242978,  0.5909451 ],
         ...,
         [ 0.48648405,  0.5658344 , -0.13323079],
         [-0.7414999 ,  0.3275252 ,  0.948064  ],
         [-0.93586904, -0.19453399, -0.47760528]],

        [[ 0.2321062 ,  0.5776786 ,  0.03806258],
         [ 1.1002092 ,  0.36440045,  0.26001576],
         [ 0.83438444, -0.14448585,  1.4778316 ],
         ...,
         [-0.82248026, -1.2253575 ,  1.4254991 ],
         [-0.85262907,  0.41728052,  0.40076151],
         [-0.12650366, -0.3388245 , -1.1100459

In [14]:
# indexing
#Obtain the pixel in the position [20,40] in the second channel of the first image.
tf_h[0][19][39][1]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.053414416>

In [15]:
# extract pixel of first ,second and fouth image  tf_h
indices = [0,1,3]
tf.gather(tf_h, indices = indices,batch_dims = 1 , axis =0)

<tf.Tensor: shape=(3, 100, 100, 3), dtype=float32, numpy=
array([[[[-9.35104370e-01,  9.06013727e-01, -1.41246632e-01],
         [-4.87768531e-01, -1.75401282e+00, -5.94542205e-01],
         [ 1.45432043e+00, -7.86842406e-02,  8.64428937e-01],
         ...,
         [-7.24449232e-02, -1.14354110e+00, -1.66517571e-01],
         [ 1.07311934e-01, -1.43393064e+00,  1.27602649e+00],
         [-2.57957280e-01, -1.21327472e+00,  5.22767365e-01]],

        [[-1.02068134e-01,  1.20898390e+00,  2.86469877e-01],
         [-2.25056097e-01,  1.14680910e+00, -9.38794076e-01],
         [-2.71305352e-01,  4.42429781e-01,  5.90945125e-01],
         ...,
         [ 4.86484051e-01,  5.65834403e-01, -1.33230790e-01],
         [-7.41499901e-01,  3.27525198e-01,  9.48064029e-01],
         [-9.35869038e-01, -1.94533989e-01, -4.77605283e-01]],

        [[ 2.32106194e-01,  5.77678621e-01,  3.80625837e-02],
         [ 1.10020924e+00,  3.64400446e-01,  2.60015756e-01],
         [ 8.34384441e-01, -1.44485846e-01

## Tensor Dimension Reduction

In [16]:
# Tensor display
const_d = tf.constant([[1,2,3,4]], shape =[2,2], dtype = tf.float32)
print(const_d.shape)


(2, 2)


In [17]:
print(const_d.get_shape())

(2, 2)


In [18]:
print(tf.shape(const_d))

tf.Tensor([2 2], shape=(2,), dtype=int32)


In [19]:
# Dimension Reshaping
reshape_1 = tf.constant([[1,2,3],[4,5,6]])
print(reshape_1)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [20]:
print(tf.reshape(reshape_1, (3,2)))

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [21]:
# Dimension Expansion

expansion_sample_1 = tf.random.normal([100,100,3], seed = 1)

In [22]:
print("The size of original of original data :" ,expansion_sample_1.shape)

The size of original of original data : (100, 100, 3)


In [23]:
print("add a dimension before the first dimension (axis = 0):",tf.expand_dims(expansion_sample_1, axis=0).shape)

add a dimension before the first dimension (axis = 0): (1, 100, 100, 3)


In [24]:
print("add a dimension before the second dimension (axis =1):", tf.expand_dims(expansion_sample_1, axis=1).shape)

add a dimension before the second dimension (axis =1): (100, 1, 100, 3)


In [25]:
print("add a dimension after the last dimension (axis = -1):",tf.expand_dims(expansion_sample_1,axis=-1).shape)

add a dimension after the last dimension (axis = -1): (100, 100, 3, 1)


In [26]:
#Transpose
transpose_1 = tf.constant([[1,2,3,4,5,6]], shape = (2,3))
print("The size of the original data",transpose_1.shape)

The size of the original data (2, 3)


In [27]:
transpose_sample = tf.transpose(transpose_1)
print("the size of transposed data:",transpose_sample)

the size of transposed data: tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


## Arithmetic Operations on Tensors

In [28]:
a = tf.constant([[3, 5], [4, 8]])
b = tf.constant([[1, 6], [2, 9]])
print(tf.add(a, b))

tf.Tensor(
[[ 4 11]
 [ 6 17]], shape=(2, 2), dtype=int32)


In [29]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 63],
       [20, 96]], dtype=int32)>

## Dimension-based Arithmetic Operations

In [30]:
reduce_sample_1 = tf.constant([1,2,3,4,5,6],shape=[2,3])
print("original data",reduce_sample_1.numpy())

original data [[1 2 3]
 [4 5 6]]


In [31]:
print("calculate the sum of all elements in the tensor (axis = None):",tf.reduce_sum(reduce_sample_1,axis=None).numpy())

calculate the sum of all elements in the tensor (axis = None): 21


In [32]:
print("calculate the sum of elements in each column by column (axis = 0):",tf.reduce_sum(reduce_sample_1,axis=0).numpy())

calculate the sum of elements in each column by column (axis = 0): [5 7 9]


In [33]:
print("calculate the sum of elements in each column by row (axis = 1):",tf.reduce_sum(reduce_sample_1,axis=1).numpy())

calculate the sum of elements in each column by row (axis = 1): [ 6 15]


## Tensor Concatenation and Splitting

In [34]:
# Tensor Concatenation
concat_sample_1 = tf.random.normal([4,100,100,3])
concat_sample_2 = tf.random.normal([40,100,100,3])
print("the size of concatnated data:", tf.concat([concat_sample_1, concat_sample_2],axis =0).shape)

the size of concatnated data: (44, 100, 100, 3)


In [35]:
stack_sample_1 = tf.random.normal([100,100,3])
stack_sample_2 = tf.random.normal([100,100,3])
print("sizes of the original data: ",stack_sample_1.shape, stack_sample_2.shape)

sizes of the original data:  (100, 100, 3) (100, 100, 3)


In [36]:
#Dimensions increase after the concatenation. If axis is set to 0, a dimension is added before the first dimension.
stacked_sample_1 = tf.stack([stack_sample_1, stack_sample_2],axis=0)
print("size of the concatenated data:",stacked_sample_1.shape)

size of the concatenated data: (2, 100, 100, 3)


In [37]:
# Tensor Splitting
# tf.unstack(): splits a tensor by a specific dimension

# tf.split(): splits a tensor into a specified number of sub tensors based on a specific dimension.
# tf.split() is more flexible than tf.unstack().

In [38]:
#Split data based on the first dimension and output the split data in a list.
tf.unstack(stacked_sample_1,axis=0)

[<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
 array([[[ 0.77538973,  0.92236835, -0.5182668 ],
         [ 0.15366296,  0.6669644 ,  0.34001115],
         [ 1.7222646 ,  0.5453355 , -0.18509527],
         ...,
         [-0.25882855,  0.67963505,  1.918344  ],
         [ 0.9817131 , -2.613872  ,  3.1824586 ],
         [-0.45913988,  0.9883884 , -1.5015342 ]],
 
        [[-0.3263565 , -0.30000684,  0.16880067],
         [ 0.23001279, -0.3491851 ,  1.3851522 ],
         [ 0.03137412,  0.23069446, -0.2966109 ],
         ...,
         [ 0.08566498,  0.3551716 ,  0.93050677],
         [ 0.04889562,  1.0192661 ,  1.160972  ],
         [-1.0532992 ,  0.378281  , -0.29878253]],
 
        [[-0.55894345,  0.593726  , -1.342291  ],
         [ 0.94858587, -1.645497  ,  0.44769812],
         [ 0.07473937,  0.30030042,  1.5530804 ],
         ...,
         [ 1.5054073 ,  1.6936663 ,  0.36163872],
         [ 1.0655934 ,  0.5435025 , -1.2288418 ],
         [-2.3759668 , -0.35432532,  1.7128898

In [39]:
import numpy as np
split_sample_1 = tf.random.normal([10,100,100,3])
print("size of the original data:",split_sample_1.shape)
splited_sample_1 = tf.split(split_sample_1, num_or_size_splits=5,axis=0)
print("size of the split data when m_or_size_splits is set to 10: ",np.shape(splited_sample_1))
splited_sample_2 = tf.split(split_sample_1, num_or_size_splits=[3,5,2],axis=0)
print("sizes of the split data when num_or_size_splits is set to [3,5,2]:",
np.shape(splited_sample_2[0]),
np.shape(splited_sample_2[1]),
np.shape(splited_sample_2[2]))

size of the original data: (10, 100, 100, 3)
size of the split data when m_or_size_splits is set to 10:  (5, 2, 100, 100, 3)
sizes of the split data when num_or_size_splits is set to [3,5,2]: (3, 100, 100, 3) (5, 100, 100, 3) (2, 100, 100, 3)


## Tensor Sorting

In [40]:
#tf.sort(): sorts tensors in ascending or descending order and returns the sorted tensors.
# tf.argsort(): sorts tensors in ascending or descending order, and returns tensor indexes.
# tf.nn.top_k(): returns the first k maximum values.tf.sort/argsort(input, direction, axis):
# input: input tensor direction: sorting order, which can be set to DESCENDING (descending order) or ASCENDING (ascending order). The default value is ASCENDING.


In [41]:
sort_sample_1 = tf.random.shuffle(tf.range(10))
print('input sample:', sort_sample_1.numpy())

input sample: [2 6 4 8 0 3 1 7 5 9]


In [42]:
sorted_sample_1 = tf.sort(sort_sample_1, direction="ASCENDING")
print("tensor sorted in ascending order:",sorted_sample_1.numpy())

tensor sorted in ascending order: [0 1 2 3 4 5 6 7 8 9]


In [43]:
sorted_sample_2 = tf.argsort(sort_sample_1,direction="ASCENDING")
print("indexes of elements in ascending order:",sorted_sample_2.numpy())

indexes of elements in ascending order: [4 6 0 5 2 8 1 7 3 9]


In [44]:
values, index = tf.nn.top_k(sort_sample_1,5)
print("input tensor:",sort_sample_1.numpy())

input tensor: [2 6 4 8 0 3 1 7 5 9]


In [45]:
print("first five values in ascending order:", values.numpy())

first five values in ascending order: [9 8 7 6 5]


In [46]:
print("indexes of the first five values in ascending order:", index.numpy())

indexes of the first five values in ascending order: [9 3 7 1 8]


In [47]:
## AutoGraph of TensorFlow 2.x

In [48]:
def simple_nn_layer(w,x,b):
    print(b)
    return tf.nn.relu(tf.matmul(w,x)+b)
w = tf.random.uniform((3,3))
x = tf.random.uniform((3,3))
b = tf.constant(0.5,dtype = 'float32')

simple_nn_layer(w,x,b)

tf.Tensor(0.5, shape=(), dtype=float32)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.70024824, 0.89947593, 1.3199432 ],
       [1.0160514 , 1.4288863 , 1.6685519 ],
       [0.61438394, 0.7361084 , 1.2879541 ]], dtype=float32)>

In [49]:
import timeit

In [50]:
#Create a convolutional layer.
CNN_cell = tf.keras.layers.Conv2D(filters=100,kernel_size=2,strides=(1,1))

In [51]:
def CNN_fn(image):
    return CNN_cell(image)

In [52]:
image = tf.zeros([100, 200, 200, 3])

In [54]:
print("time required for performing the computation of one convolutional neural network (CNN) 
      layer in eager execution mode:", timeit.timeit(lambda: CNN_cell(image), number=10))

time required for performing the computation of one convolutional neural network (CNN) layer in eager execution mode: 34.13967268399574


In [55]:
print("time required for performing the computation of one CNN layer in graph mode:",
      timeit.timeit(lambda: CNN_fn(image), number=10))

time required for performing the computation of one CNN layer in graph mode: 14.809246119002637


## Common Modules of TensorFlow 2.x

In [ ]:
#  tf.data: implements operations on datasets.
#These operations include reading datasets directly from the memory, reading CSV files,
#reading TFRecord files, and augmenting data.
#  tf.image: implements processing operations on images.
#These operations include image luminance transformation, saturation transformation,
#image size transformation, image rotation, and edge detection.
#  tf.gfile: implements operations on files.
#These operations include reading, writing, and renaming files, and operating folders.
#  tf.keras: a high-level API used to build and train deep learning models.
#  tf.distributions and other modules
#This section focuses on the tf.keras module to lay a foundation for deep learning modeling.

## MODEL BUILDING

In [ ]:
# Stacking a Model (tf.keras.Sequential)
